### ISSUE TITLE
Decide which db we want to use

### ISSUE THREAD

**Issue by nihalpd** [nihalpd/Fikky#1]
Decide which db we want to use to store our stories.

**Comment by ykcab** [comment]
MySQL tend to be a good solution. We also have PostgreSQL (Never used it before).
Here are few resources to get started with some relational databases:
- MariaDB driver connector: https://downloads.mariadb.org/connector-java/
- MySQL : https://dev.mysql.com/doc/connector-j/5.1/en/
I only picked the above because of their open source. The MariaDB come to play the game because some Linux distro pushes to install MariaDB.

**Comment by nihalpd** [comment]
I was also thinking about postgresql, but i think we can stick to mysql for now and switch out later, as the java code will be the same either way. we just have to go about defining our objects.

**Comment by ykcab** [comment]
Picked A DB : MySQL will be later hosted on Heroku
